language: php

php: 7.4

branches:
    only:
        - master

install:
    - composer update

scripts:
    # tweet a new post
    # get tokens to Travis ENV: https://travis-ci.com/TomasVotruba/tomasvotruba.com/settings
    # from here: https://developer.twitter.com/en/apps/14147884
    - bin/console tweet

    # build static version to /output directory
    # used for deploy
    - bin/console dump-static-site --ansi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output
