language: php

php: 7.0

env:
  global:
    - secure: WDXxKdn/KAhCQA/Ajo2aDQPc0sYjDJU/2dJMumZc+l/TflSIa9QG7ZZmr2GRS/ml+4RzOzPK+99mXWZYKKfbmKSZTonp2jaX6xTiZ6pfZklSQ6qmg7jFVi+WCp8ii6tgn+HRGtcciuyXqsI6g8IYbG2QJZuyThyCqhXCuYtPDcPQzYgQ3eELgHbQ8J9ZqXMr9BiugJ297V87839RB1CS2YtbqrB7ku/gEwLfFO0ZQr2tGcr4NgZVImMQXU9yCWQjMsG9sSqlyG5wFv5UFEvVn8puMWi1CtJ6biPv6m+kpKkssAtg1HObCaQ7ZUTNxsGEsUinhz1fTCr64GXUbnZaIuFSD3pa2N8319O/ghG0VsagJvStn3ScUvpAvLIGRl+OennS3fGlt3Qk+ooSzZnbn3TOdOPlfQmQ9LaV0ieV86ks+ZFOlXpKGuIa4K5TxR3W3oBQhQEImE11yYcPp+uj0Bc88bkdGcj2cYfA/6OSKcp7z+/1VE9UsvRld5fEr+mUJbnpfGGtE54sCdS4Y2l8oVx54C7JDhPC5qhx7dWPX0S8uXJ6c0h/MyvqakB40LyKJBgJ19FzlpUDJIeBqJ9ADDxFBcjvIysW8c0Ej8z/DJn/VVZQI9GFBM3ayqDyyFJMxr2FhwcOE6WaLZHOb2h7JYZXYVNDkwEKits7ihC6BOA=

before_script:
    - composer self-update
    - composer update --prefer-source

script:
    - ./bin/deploy-gh-pages.sh
