language: php

php: '7.3'

install:
    - composer install

script:
    - vendor/bin/phpunit

    # static analysis
    - composer check-cs
    - composer phpstan

    # test that website is generated
    - vendor/bin/statie generate source

    # check updates with Rector
    - vendor/bin/rector process src tests --dry-run

    # dump contributors before deploy
#    - |
#      if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
#          vendor/bin/statie dump-contributors
#      fi

# see docs: https://www.statie.org/docs/github-pages/
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output

after_deploy:
    # tweets posts
    - |
      if [[ $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
          vendor/bin/statie tweet-post
      fi

notifications:
    email:
        on_success: never
        on_failure: always
