language: php

matrix:
    include:
        - php: 7.3

install:
    - composer update

branches:
    only:
        - master
script:
    # build static version to /output directory
    - bin/console dump-static-site --ansi

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output
