# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

php: 7.4

jobs:
    include:
        -
            name: 'Tweet new Post'
            if: branch = master
            script:
                - vendor/bin/statie tweet-post

notifications:
    email: false
