language: php

php:
    - '7.3'
    - '7.4snapshot'

install:
    - composer install

jobs:
    include:
        -
            stage: test
            name: ECS
            php: 7.3
            script:
                - composer check-cs

        -
            name: PHPStan
            php: 7.3
            script:
                - composer phpstan

        -
            name: Rector
            php: 7.3
            script:
                - vendor/bin/rector process src tests --dry-run --config rector-ci.yaml

        -
            name: 'Unit Tests'
            script:
                - vendor/bin/phpunit

        -
            stage: deploy
            name: 'Deploy to Github Pages'
            if: branch = master AND type = push
            php: 7.3
            # see docs: https://www.statie.org/docs/github-pages/
            script:
                - vendor/bin/statie generate source
#            before_deploy:
#                - vendor/bin/statie dump-contributors
            deploy:
                -
                    provider: pages
                    skip_cleanup: true
                    github_token: $GITHUB_TOKEN
                    on:
                        branch: master
                    local_dir: output

        -
            stage: tweet
            name: 'Tweet new Post'
            if: branch = master AND type = push
            php: 7.3
            script:
                - vendor/bin/statie tweet-post

    allow_failures:
        - php: '7.4snapshot'

matrix:
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        on_success: never
