# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

dist: bionic

php: 7.4

before_install:
    - phpenv config-rm xdebug.ini

jobs:
    include:
        -
            stage: tweet
            name: 'Tweet new Post'
            if: branch = master
            script:
                - vendor/bin/statie tweet-post

notifications:
    email: false

