language: php

php: 7.4

install:
    - composer update

branches:
    only:
        - master

script:
    # build static version to /output directory
    # used for deploy
    - bin/console dump-static-site --ansi

jobs:
    include:
        -
            name: 'Tweet new Post'
            script:
                - composer install
                # get tokens to Travis ENV: https://travis-ci.com/TomasVotruba/tomasvotruba.com/settings
                # from here: https://developer.twitter.com/en/apps/14147884
                - bin/console tweet

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: output
