language: php

php:
    - '7.3'
    - '7.4'

install:
    - composer install

jobs:
    include:
        -
            stage: test
            name: ECS
            php: 7.3
            script:
                - composer check-cs

        -
            name: PHPStan
            php: 7.3
            script:
                - composer phpstan

        -
            name: Rector
            php: 7.3
            script:
                - composer rector

        -
            name: 'Unit Tests'
            script:
                - vendor/bin/phpunit

        -
            stage: tweet
            name: 'Tweet new Post'
            if: branch = master
            php: 7.3
            script:
                - vendor/bin/statie tweet-post

    allow_failures:
        - name: 'Rector'

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email:
        on_success: never
