# inspired by https://github.com/rectorphp/rector/blob/master/.travis.yml
language: php

php: 7.4

branches:
    only:
        - master

jobs:
    include:
        -
            name: 'Tweet new Post'
            script:
                - composer install
                # get tokens to Travis ENV: https://travis-ci.com/TomasVotruba/tomasvotruba.com/settings
                # from here: https://developer.twitter.com/en/apps/14147884
                - bin/console tweet-post

notifications:
    email: false
