# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Tweet Post

on:
    push:
        branches:
            - master

jobs:
    tweet_post:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.4
                    coverage: none

            -   run: composer install --no-progress

            -
                name: Tweet New Post
                run: |
                    bin/console tweet-post
                env:
                    # get tokens to Github Secrets:
                    # from here: https://developer.twitter.com/en/apps/14147884
                    TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
                    TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
                    TWITTER_OAUTH_ACCESS_TOKEN: ${{ secrets.TWITTER_OAUTH_ACCESS_TOKEN }}
                    TWITTER_OAUTH_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_OAUTH_ACCESS_TOKEN_SECRET }}
