framework:
    # Uncomment the 'ide' option to turn all of the file paths in an exception
    # page into clickable links that open the given file using your favorite IDE.
    # Supported values are 'textmate', 'macvim', 'emacs' and 'sublime' shortcuts
    # and any custom configuration string, such as: "phpstorm://open?file=%%f&line=%%l"
    # See http://symfony.com/doc/current/reference/configuration/framework.html#ide
    ide: sublime
    assets: true

    # esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection:
        enabled: true
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
