homepage:
    path: /
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'default/homepage.html.twig'

blog:
    resource: @BlogDomainBundle/Resources/config/routing/main.yml

app:
    resource: @BlogDomainBundle/Controller/
    type:     annotation
