# use in a template as {{ site.title }}
title: Tomáš Votruba - Nette a Symfony školení
disqus_shortname: itsworthsharing
google_analytics_tracking_id: "UA-46082345-1"
url: "http://www.tomasvotruba.cz"
