services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    TomasVotruba\CleaningLady\:
        resource: '../src'
        exclude:
            - '../src/ValueObject/*'
