parameters:
    twitter_name: '%env(TWEETER_NAME)%'

    twitter_minimal_gap_in_days: 1 # how many days to wait before publishing another Tweet
    twitter_maximal_days_in_past: 300 # how old Tweets should be tweeted, to prevent 2-years old posting

    twitter_consumer_key: '%env(TWITTER_CONSUMER_KEY)%'
    twitter_consumer_secret: '%env(TWITTER_CONSUMER_SECRET)%'
    twitter_oauth_access_token: '%env(TWITTER_OAUTH_ACCESS_TOKEN)%'
    twitter_oauth_access_token_secret: '%env(TWITTER_OAUTH_ACCESS_TOKEN_SECRET)%'

services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    TomasVotruba\Tweeter\:
        resource: '../src'
        exclude:
            - '../src/Exception/*'
            - '../src/ValueObject/*'

    TwitterAPIExchange:
        class: 'TwitterAPIExchange'
        factory: ['@TomasVotruba\Tweeter\TwitterApi\TwitterApiFactory', 'create']

    Symplify\SmartFileSystem\FileSystemGuard: null
