imports:
    - { resource: '../../packages/ContribThanker/src/config/config.yml' }

services:
    _defaults:
        public: true
        autowire: true

    Symfony\Component\Console\Application: ~

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: ~
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
