parameters:
    twitter_name: 'VotrubaT'
    source_directory: '%kernel.project_dir%/../../../source'
    minimal_gap_in_days: 4 # how many days to wait before publishing another Tweet

    twitter_consumer_key: "..."
    twitter_consumer_secret: "..."
    twitter_oauth_access_token: "..."
    twitter_oauth_access_token_secret: "..."

services:
    _defaults:
        autowire: true

    # PSR-4 autodiscovery
    TomasVotruba\Website\TweetPublisher\:
        resource: "%kernel.project_dir%/../../../src/TweetPublisher"

    TomasVotruba\Website\TweetPublisher\PostTweetsProvider:
        arguments:
            - '%site_url%'
            - '%source_directory%'

    TomasVotruba\Website\TweetPublisher\TwitterApi\TwitterApiWrapper:
        arguments:
            - '%twitter_name%'

    TomasVotruba\Website\TweetPublisher\TweetPublisher:
        public: true # for bin/tweet-new-posts container fetch
        arguments:
            - '%minimal_gap_in_days%'

    # Twitter API
    TomasVotruba\Website\TweetPublisher\TwitterApi\TwitterApiFactory:
        arguments:
            - '%twitter_consumer_key%'
            - '%twitter_consumer_secret%'
            - '%twitter_oauth_access_token%'
            - '%twitter_oauth_access_token_secret%'

    TwitterAPIExchange:
        class: TwitterAPIExchange
        factory: ['@TomasVotruba\Website\TweetPublisher\TwitterApi\TwitterApiFactory', 'create']
