services:
    blog.twig_extension:
        class: TomasVotruba\SculpinBlogBundle\Twig\SculpinBlogExtension
        arguments:
            - @sculpin_twig.loader
        tags:
            - { name: twig.extension }
