imports:
    - { resource: "parameters.yaml" }

services:
    _defaults:
        public: true
        autowire: true

    TomasVotruba\FrameworkStats\:
        resource: "../src"
        exclude:
            - "../src/HttpKernel/*"

