parameters:
    # used by https://www.tomasvotruba.cz/php-framework-trends/
    frameworks_vendor_to_name:
        nette: Nette
        symfony: Symfony
        # includes also laravel/framework
        illuminate: Laravel
        cakephp: CakePHP
        # single monorepos
        zendframework: Zend
        yiisoft: Yii
        # db "frameworks"
        doctrine: Doctrine

    excluded_framework_packages:
        # out there, but too fresh (remove in 2020)
        - 'symfony/security-guard'
        - 'symfony/security-http'
        - 'symfony/security-csrf'

        # framework irrelevant
        - 'symfony/lts'
        - 'symfony/thanks'

        # rather "utils" packages
        - 'symfony/polyfill'
        - 'symfony/polyfill-*'

        # pseudo-packages
        - 'symfony/*-pack'
        - 'symfony/*-bundle'

        # deprecated
        - 'symfony/class-loader'
        - 'symfony/assetic-bundle'
        - 'symfony/locale'
        - 'symfony/icu'
        - 'symfony/swiftmailer-bridge'
        - 'illuminate/html'

        # specific integrations
        - 'doctrine/*-module'
        - 'doctrine/*-bundle'
        - 'doctrine/static-website-generator'
        - 'doctrine/doctrine1'
        - 'doctrine/coding-standard'

        # weak packages
        - 'cakephp/elastic-search'
        - 'cakephp/acl'
        - 'yiisoft/yii2-apidoc'
        - 'zendframework/zend-expressive-*'
        - 'zendframework/skeleton-application'
        - 'zendframework/zend-config-*'
        - 'zendframework/zend-developer-tools'

        # meta packages
        - '*/contracts'
        - 'symfony/*-contracts'
        - 'symfony/symfony1'
        - 'symfony/symfony-demo'
        - 'symfony/skeleton'
        - 'symfony/requirements-checker'
        - 'symfony/framework-standard-edition'
        - 'symfony/force-lowest'
        - 'symfony/image-fixtures'
        - 'symfony/*-bridge'
        - 'symfony/symfony-installer'

        # nette meta packages
        - 'nette/sandbox'
        - 'nette/nette-minified'
        - 'nette/deprecated'
        - 'nette/extras'
        - 'nette/coding-standard'
        - 'nette/code-checker'
        - 'nette/addon-installer'
        - 'nette/type-fixer'
        - 'nette/web-project'
