parameters:
    thanker_repository_name: "tomasvotruba/tomasvotruba.com"
    thanker_author_name: "TomasVotruba"

    # create token here: https://github.com/settings/tokens/new
    # use in cli like: "GITHUB_TOKEN=%s vendor/bin/monorepo-builder split ..."
    github_token: '%env(GITHUB_TOKEN)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    TomasVotruba\GithubContributorsThanker\:
        resource: '../src'
        exclude:
            - '../src/Exception/*'

    Symfony\Component\Filesystem\Filesystem: null

    Symplify\PackageBuilder\Http\BetterGuzzleClient: null
    GuzzleHttp\Client: null
