# see https://github.com/marketplace/actions/deploy-to-github-pageshttps://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy

on:
    push:
        branches:
            - master

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v1
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: vendor/bin/statie generate source

            -
                name: Deploy
                uses: JamesIves/github-pages-deploy-action@releases/v3
                with:
                    ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output

    tweet_post:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress

            -
                name: Tweet New Post
                run: |
                    vendor/bin/statie tweet-post
                env:
                    TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
                    TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
                    TWITTER_OAUTH_ACCESS_TOKEN: ${{ secrets.TWITTER_OAUTH_ACCESS_TOKEN }}
                    TWITTER_OAUTH_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_OAUTH_ACCESS_TOKEN_SECRET }}
